### ISSUE TITLE
Create sketches of desired outcomes

### ISSUE THREAD

**Issue by johnshaughnessy** [johnshaughnessy/physics-adventure#16]
Can be on paper, but would ideally be digital images created with GIMP

Think: Different Users for possibilities (i.e. Teacher, Student, Physics Enthusiast, Cat)

**Comment by notyourkey** [comment]
Create Separate Comic Books For What User Experience is Like

From Minimal Effort -> Maximum Effort
A.K.A. Most Doable -> Most Dreamy
